version: '3.8'

services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITBD_ROOT_USERNAME = dio
      - MONGO_INITBD_ROOT_PASSWORD = dio
    ports:
      - "27017:27017"
    volumes:
      - /srv/www/raiz/diversos/dio/diversos/NoSQLStudies/volumes/dbdata: /data/db