version: '3.8'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dio
      - MONGO_INITDB_ROOT_PASSWORD=dio
    volumes:
      - /srv/www/raiz/diversos/dio/diversos/NoSQLStudies/volumes/database:/data/db